all: run1 run2 run3 run4 run5 run6 run7 run8 run9 run10 run11 run12 run13 run14 run15 run16 run17 run18 run19 run20 run21 run22

run1:
	@echo "Task 1"
	@./bin/task1.exe

run2:
	@echo "Task 2"
	@./bin/task2.exe

run3:
	@echo "Task 3"
	@./bin/task3.exe

run4:
	@echo "Task 4"
	@cd task4 && ../bin/task4.exe

run5:
	@echo "Task 5"
	@./bin/task5.exe

run6:
	@echo "Task 6"
	@cd task6 && ../bin/task6.exe

run7:
	@echo "Task 7"
	@./bin/task7.exe

run8:
	@echo "Task 8"
	@./bin/task8.exe

run9:
	@echo "Task 9"
	@./bin/task9.exe

run10:
	@echo "Task 10"
	@./bin/task10.exe

run11:
	@echo "Task 11"
	@./bin/task11.exe

run12:
	@echo "Task 12"
	@./bin/task12.exe

run13:
	@echo "Task 13"
	@./bin/task13.exe

run14:
	@echo "Task 14"
	@./bin/task14.exe

run15:
	@echo "Task 15"
	@./bin/task15.exe

run16:
	@echo "Task 16"
	@cd task16 && ../bin/task16.exe

run17:
	@echo "Task 17"
	@cd task17 && ../bin/task17.exe

run18:
	@echo "Task 18"
	@./bin/task18.exe

run19:
	@echo "Task 19"
	@cd task19 && ../bin/task19.exe

run20:
	@echo "Task 20"
	@./bin/task20.exe

run21:
	@echo "Task 21"
	@./bin/task21.exe

run22:
	@echo "Task 22"
	@./bin/task22.exe

.PHONY: all run1 run2 run3 run4 run5 run6 run7 run8 run9 run10 run11 run12 run13 run14 run15 run16 run17 run18 run19 run20 run21 run22