run-task1:
	@echo " "
	@echo "=== Запуск Task 1: Динамическая структура с указателем на статическую ==="
	./bin/task1

run-task2:
	@echo " "
	@echo "=== Запуск Task 2: Динамическая структура по номеру задачи ==="
	./bin/task2

run-individ-task1:
	@echo " "
	@echo "=== Запуск Individual Task 1: Стек на односвязном списке ==="
	./bin/individ_task1

run-individ-tasks-2-3:
	@echo " "
	@echo "=== Запуск Individual Tasks 2&3: Двусвязный список ==="
	./bin/individ_tasks_2_and_3

run-individ-task4:
	@echo " "
	@echo "=== Запуск Individual Task 4: Циклический двусвязный список ==="
	./bin/individ_task4

run-individ-task5:
	@echo " "
	@echo "=== Запуск Individual Task 5: Циклический односвязный список ==="
	./bin/individ_task5

run-all: run-task1 run-task2 run-individ-task1 run-individ-tasks-2-3 run-individ-task4 run-individ-task5

.DEFAULT_GOAL := run-all
